##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.13.0-B3] date: [Mon Jan 24 09:35:33 CST 2022]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = H7FC

HW_MATEK_STM32H743 := 0
HW_MATEK_STM32H743 := 1
HW_BATEAIO_AT32F435 := 2

BUILD_TYPE := $(HW_MATEK_STM32H743)

######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
main.c \
Algorithm/Navi_Dep/MadgwickAHRS.c \
Algorithm/Filter_Dep/filter.c \
Algorithm/Filter_Dep/filter_param.c \
Algorithm/Control_Dep/adrc.c \
Algorithm/Control_Dep/pid.c \
debug/debug_util.c \
Task/Task_Navi.c \
Task/Task_Manager.c \
Task/Task_Sample.c \
Task/Task_Log.c \
Task/Task_Telemetry.c \
Task/Task_Protocol.c \
Task/Task_Control.c \
IO_Def/IO_Definition.c \
Bsp/Bsp_GPIO.c \
Bsp/Bsp_SPI.c \
Bsp/Bsp_SDMMC.c \
Bsp/Bsp_Uart.c \
Bsp/Bsp_USB.c \
Bsp/Bsp_Flash.c \
Bsp/Bsp_DMA.c \
Bsp/Bsp_Timer.c \
Bsp/Bsp_IIC.c \
Device/Dev_DPS310.c \
Device/Dev_MPU6000.c \
Device/Dev_ICM20602.c \
Device/Dev_ICM426xx.c \
Device/Dev_Led.c \
Device/Dev_W25Qxx.c \
Device/Dev_Card.c \
Device/Dev_Sbus.c \
Device/Dev_CRSF.c \
Device/Dev_Dshot.c \
Service/Srv_IMUSample.c \
Service/Srv_Baro.c \
Service/Srv_Receiver.c \
Service/Srv_Actuator.c \
Service/Srv_ComProto.c \
Service/Srv_DataHub.c \
Service/Srv_OsCommon.c \
Service/Srv_SensorMonitor.c \
Service/Srv_CtlDataArbitrate.c \
DataStructure/Data_Convert_Util.c \
DataStructure/CusQueue.c \
DataStructure/linked_list.c \
DataStructure/binary_tree.c \
common/reboot.c \
common/error_log.c \
common/util.c \
common/compess/minilzo.c \
System/storage/Storage.c \
System/DataPipe/DataPipe.c \
System/DataPipe/DataPipe_Def.c \
System/FreeRTOS/croutine.c \
System/FreeRTOS/event_groups.c \
System/FreeRTOS/list.c \
System/FreeRTOS/freertos.c \
System/FreeRTOS/queue.c \
System/FreeRTOS/stream_buffer.c \
System/FreeRTOS/tasks.c \
System/FreeRTOS/timers.c \
System/FreeRTOS/CMSIS_RTOS/cmsis_os.c \
System/FreeRTOS/portable/MemMang/heap_4.c \
System/FreeRTOS/portable/GCC/ARM_CM4F/port.c \
System/kernel/kernel.c \
System/diskio/DiskIO.c \
System/shell/shell_cmd_list.c \
System/shell/shell_companion.c \
System/shell/shell_ext.c \
System/shell/shell_port.c \
System/shell/shell.c
ifeq ($(BUILD_TYPE), $(HW_MATEK_STM32H743))
C_SOURCES +=  \
HW_Lib/STM32H7/USB/USB_DEVICE/App/usb_device.c \
HW_Lib/STM32H7/USB/USB_DEVICE/App/usbd_desc.c \
HW_Lib/STM32H7/USB/USB_DEVICE/App/usbd_cdc_if.c \
HW_Lib/STM32H7/USB/USB_DEVICE/Target/usbd_conf.c \
HW_Lib/STM32H7/USB/STM32_USB_Device_Library/Core/Src/usbd_core.c \
HW_Lib/STM32H7/USB/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
HW_Lib/STM32H7/USB/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c \
HW_Lib/STM32H7/USB/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c  \
HW_Lib/STM32H7/HAL_Lib/Core/Src/stm32h7xx_it.c \
HW_Lib/STM32H7/HAL_Lib/Core/Src/system_stm32h7xx.c  \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd_ex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sd.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_sdmmc.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_usb.c \

# ASM sources
ASM_SOURCES =  \
startup_stm32h743xx.s

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32H743VIHx_FLASH.ld

#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m7

else ifeq ($(BUILD_TYPE), $(HW_MATEK_STM32H743))
C_SOURCES +=  \
HW_Lib/STM32H7/USB/USB_DEVICE/App/usb_device.c \
HW_Lib/STM32H7/USB/USB_DEVICE/App/usbd_desc.c \
HW_Lib/STM32H7/USB/USB_DEVICE/App/usbd_cdc_if.c \
HW_Lib/STM32H7/USB/USB_DEVICE/Target/usbd_conf.c \
HW_Lib/STM32H7/USB/STM32_USB_Device_Library/Core/Src/usbd_core.c \
HW_Lib/STM32H7/USB/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
HW_Lib/STM32H7/USB/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c \
HW_Lib/STM32H7/USB/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c  \
HW_Lib/STM32H7/HAL_Lib/Core/Src/stm32h7xx_it.c \
HW_Lib/STM32H7/HAL_Lib/Core/Src/system_stm32h7xx.c  \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd_ex.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sd.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_sdmmc.c \
HW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_usb.c \

ASM_SOURCES =  \
startup_at32f435_437.s

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = AT32F435xG_FLASH.ld

#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4
endif

#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

ifeq ($(BUILD_TYPE), $(HW_MATEK_STM32H743))
# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32H743xx \

# fpu
FPU = -mfpu=fpv5-d16
endif

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-IIO_Def/ \
-Idebug/ \
-IBsp/ \
-ITask/ \
-IDevice/ \
-Icommon/ \
-Icommon/compess \
-IService/ \
-ISystem/FreeRTOS \
-ISystem/FreeRTOS/include \
-ISystem/FreeRTOS/CMSIS_RTOS \
-ISystem/FreeRTOS/portable/GCC/ARM_CM4F \
-ISystem/shell \
-ISystem/storage \
-ISystem/diskio \
-Idebug \
-IMAVLink \
-IAlgorithm/Navi_Dep \
-IAlgorithm/Filter_Dep \
-IAlgorithm/Control_Dep \
-IAlgorithm \
-IMAVLink/common \
-IMAVLink/minimal \
-IMAVLink/standard \
-IDataStructure/ \
-ISystem/kernel/ \
-ISystem/DataPipe 
ifeq ($(BUILD_TYPE), $(HW_MATEK_STM32H743))
C_INCLUDES +=  \
-IHW_Lib/STM32H7/HAL_Lib/STM32H7xx_HAL_Driver/Inc \
-IHW_Lib/STM32H7/HAL_Lib/Core/Inc \
-IHW_Lib/STM32H7/HAL_Lib/CMSIS/Device/ST/STM32H7xx/Include \
-IHW_Lib/STM32H7/HAL_Lib/CMSIS/Core/Include \
-IHW_Lib/STM32H7/HAL_Lib/CMSIS/Device/ST/STM32H7xx/Include \
-IHW_Lib/STM32H7/HAL_Lib/CMSIS/Include \
-IHW_Lib/STM32H7/USB/STM32_USB_Device_Library/Core/Inc \
-IHW_Lib/STM32H7/USB/STM32_USB_Device_Library/Class/CDC/Inc \
-IHW_Lib/STM32H7/USB/USB_DEVICE/App \
-IHW_Lib/STM32H7/USB/USB_DEVICE/Target
else ifeq ($(BUILD_TYPE), $(HW_BATEAIO_AT32F435))
C_INCLUDES += 
endif

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

# ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
# endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

# Hardware defines
ifeq ($(BUILD_TYPE), $(HW_MATEK_STM32H743))
CFLAGS += -DMATEKH743_V1_5
else ifeq ($(BUILD_TYPE), $(HW_BATEAIO_AT32F435))
CFLAGS += -DBATEAT32F435_AIO
endif

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

ifeq ($(BUILD_TYPE), $(HW_MATEK_STM32H743))
OPENOCD := openocd -f interface/stlink.cfg \
        -f target/stm32h7x.cfg 
else ifeq ($(BUILD_TYPE), $(HW_BATEAIO_AT32F435))
OPENOCD := openocd -f interface/stlink.cfg \
        -f target/stm32f4x.cfg 
endif

# download your program
# $(OPENOCD)
# -c 'program $(BUILD_DIR)/$(TARGET).elf verify reset run exit' 
flash: all
	$(OPENOCD) -c init \
		-c 'reset halt' \
		-c 'flash write_image erase $(BUILD_DIR)/$(TARGET).elf' \
		-c 'reset run' \
		-c exit

debug:
	$(OPENOCD)

