/*
 * code: 8_B!T0
 * bref: all butterworth filter parameter generated by matlab fdatool
 */
#include "filter_param.h"

/*
 *  low pass filter parameter section
 */

/*
 * 1K Sample Rate Section
 */
/* 2 order butterworth filter parameter / stop frequence: 30Hz / sample rate: 1K */
const BTF_Para_TypeDef BTF_E_2O_30Hz_1K[3] = {{0.00782020803349719, DEFAULT_PARAM_SCALE}, {0.0156404160669944, DEFAULT_PARAM_SCALE}, {0.00782020803349719, DEFAULT_PARAM_SCALE}};
const BTF_Para_TypeDef BTF_U_2O_30Hz_1K[2] = {{-1.73472576880928, DEFAULT_PARAM_SCALE}, {0.766006600943264, DEFAULT_PARAM_SCALE}};

/* 2 order butterworth filter parameter / stop frequence: 50Hz / sample rate: 1K */
const BTF_Para_TypeDef BTF_E_2O_50Hz_1K[3] = {{0.0200833655642112, DEFAULT_PARAM_SCALE}, {0.0401667311284225, DEFAULT_PARAM_SCALE}, {0.0200833655642112, DEFAULT_PARAM_SCALE}};
const BTF_Para_TypeDef BTF_U_2O_50Hz_1K[2] = {{-1.56101807580072, DEFAULT_PARAM_SCALE}, {0.641351538057563, DEFAULT_PARAM_SCALE}};

/* 3 order butterworth filter parameter / stop frequence: 30Hz / sample rate: 1K */
const BTF_Para_TypeDef BTF_E_3O_30Hz_1K[4] = {{0.000699349649901005, DEFAULT_PARAM_SCALE}, {0.00209804894970302, DEFAULT_PARAM_SCALE}, {0.00209804894970302, DEFAULT_PARAM_SCALE}, {0.000699349649901005, DEFAULT_PARAM_SCALE}};
const BTF_Para_TypeDef BTF_U_3O_30Hz_1K[3] = {{-2.62355180660524, DEFAULT_PARAM_SCALE}, {2.31468258108911, DEFAULT_PARAM_SCALE}, {-0.685535977284664, DEFAULT_PARAM_SCALE}};

/* 3 order butterworth filter parameter / stop frequence: 50Hz / sample rate: 1K */
const BTF_Para_TypeDef BTF_E_3O_50Hz_1K[4] = {{0.00289819463372143, DEFAULT_PARAM_SCALE}, {0.00869458390116429, DEFAULT_PARAM_SCALE}, {0.00869458390116429, DEFAULT_PARAM_SCALE}, {0.00289819463372143, DEFAULT_PARAM_SCALE}};
const BTF_Para_TypeDef BTF_U_3O_50Hz_1K[3] = {{-2.37409474370935, DEFAULT_PARAM_SCALE}, {1.92935566909122, DEFAULT_PARAM_SCALE}, {-0.532075368312092, DEFAULT_PARAM_SCALE}};

/* 4 order butterworth filter parameter / stop frequence: 30Hz / sample rate: 1K */
const BTF_Para_TypeDef BTF_E_4O_30Hz_1K[5] = {{6.23869835484794, 1e-05}, {0.000249547934193918, DEFAULT_PARAM_SCALE}, {0.000374321901290876, DEFAULT_PARAM_SCALE}, {0.000249547934193918, DEFAULT_PARAM_SCALE}, {6.23869835484794, 1e-05}};
const BTF_Para_TypeDef BTF_U_4O_30Hz_1K[4] = {{-3.50778620739078, DEFAULT_PARAM_SCALE}, {4.64090241268671, DEFAULT_PARAM_SCALE}, {-2.74265282112037, DEFAULT_PARAM_SCALE}, {0.610534807561224, DEFAULT_PARAM_SCALE}};

/* 4 order butterworth filter parameter / stop frequence: 50Hz / sample rate: 1K */
const BTF_Para_TypeDef BTF_E_4O_50Hz_1K[5] = {{0.000416599204406599, DEFAULT_PARAM_SCALE}, {0.00166639681762640, DEFAULT_PARAM_SCALE}, {0.00249959522643960, DEFAULT_PARAM_SCALE}, {0.00166639681762640, DEFAULT_PARAM_SCALE}, {0.000416599204406599, DEFAULT_PARAM_SCALE}};
const BTF_Para_TypeDef BTF_U_4O_50Hz_1K[4] = {{-3.18063854887472, DEFAULT_PARAM_SCALE}, {3.86119434899421, DEFAULT_PARAM_SCALE}, {-2.11215535511097, DEFAULT_PARAM_SCALE}, {0.438265142261980, DEFAULT_PARAM_SCALE}};

/* 5 order butterworth filter parameter / stop frequence: 30Hz / sample rate: 1K */
const BTF_Para_TypeDef BTF_E_5O_30Hz_1K[6] = {{5.56030909572733, 1e-06}, {2.78015454786367, 1e-05}, {5.56030909572733, 1e-05}, {5.56030909572733, 1e-05}, {2.78015454786367, 1e-05}, {5.56030909572733, 1e-06}};
const BTF_Para_TypeDef BTF_U_5O_30Hz_1K[5] = {{-4.39027619426085, DEFAULT_PARAM_SCALE}, {7.74286954080104, DEFAULT_PARAM_SCALE}, {-6.85434935089592, DEFAULT_PARAM_SCALE}, {3.04468530918026, DEFAULT_PARAM_SCALE}, {-0.542751374933465, DEFAULT_PARAM_SCALE}};

/* 5 order butterworth filter parameter / stop frequence: 50Hz / sample rate: 1K */
const BTF_Para_TypeDef BTF_E_5O_50Hz_1K[6] = {{5.97957803700032, 1e-05}, {0.000298978901850016, DEFAULT_PARAM_SCALE}, {0.000597957803700032, DEFAULT_PARAM_SCALE}, {0.000597957803700032, DEFAULT_PARAM_SCALE}, {0.000298978901850016, DEFAULT_PARAM_SCALE}, {5.97957803700032, 1e-05}};
const BTF_Para_TypeDef BTF_U_5O_50Hz_1K[5] = {{-3.98454311961234, DEFAULT_PARAM_SCALE}, {6.43486709027587, DEFAULT_PARAM_SCALE}, {-5.25361517035227, DEFAULT_PARAM_SCALE}, {2.16513290972413, DEFAULT_PARAM_SCALE}, {-0.359928245063556, DEFAULT_PARAM_SCALE}};

/*
 * 2K Sample Rate section
 */
/* 2 order butterworth filter parameter / stop frequence: 30Hz / sample rate: 2K */
// const BTF_Para_TypeDef BTF_E_2O_30Hz_2K[3];
// const BTF_Para_TypeDef BTF_U_2O_30Hz_2K[2];

/* 2 order butterworth filter parameter / stop frequence: 50Hz / sample rate: 2K */
// const BTF_Para_TypeDef BTF_E_2O_50Hz_2K[3];
// const BTF_Para_TypeDef BTF_U_2O_50Hz_2K[2];

/* 3 order butterworth filter parameter / stop frequence: 30Hz / sample rate: 2K */
// const BTF_Para_TypeDef BTF_E_3O_30Hz_2K[4];
// const BTF_Para_TypeDef BTF_U_3O_30Hz_2K[3];

/* 3 order butterworth filter parameter / stop frequence: 50Hz / sample rate: 2K */
// const BTF_Para_TypeDef BTF_E_3O_50Hz_2K[4];
// const BTF_Para_TypeDef BTF_U_3O_50Hz_2K[3];

/* 4 order butterworth filter parameter / stop frequence: 30Hz / sample rate: 2K */
// const BTF_Para_TypeDef BTF_E_4O_30Hz_2K[5];
// const BTF_Para_TypeDef BTF_U_4O_30Hz_2K[4];

/* 4 order butterworth filter parameter / stop frequence: 50Hz / sample rate: 2K */
// const BTF_Para_TypeDef BTF_E_4O_50Hz_2K[5];
// const BTF_Para_TypeDef BTF_U_4O_50Hz_2K[4];

/* 5 order butterworth filter parameter / stop frequence: 30Hz / sample rate: 2K */
// const BTF_Para_TypeDef BTF_E_5O_30Hz_2K[6];
// const BTF_Para_TypeDef BTF_U_5O_30Hz_2K[5];

/* 5 order butterworth filter parameter / stop frequence: 50Hz / sample rate: 2K */
// const BTF_Para_TypeDef BTF_E_5O_50Hz_2K[6] = {{2.3409914930614, 1e-06}, {1.1704957465307, 1e-05}, {2.3409914930614, 1e-05}, {2.3409914930614, 1e-05}, {1.1704957465307, 1e-05}, {2.3409914930614, 1e-06}};
// const BTF_Para_TypeDef BTF_U_5O_50Hz_2K[5] = {{-4.49183096507705, DEFAULT_PARAM_SCALE}, {8.09405541782665, DEFAULT_PARAM_SCALE}, {-7.31208128015038, DEFAULT_PARAM_SCALE}, {3.31104756198840, DEFAULT_PARAM_SCALE}, {-0.601115822859839, DEFAULT_PARAM_SCALE}};

/*
 * 4K Sample Rate section
 */
/* 2 order butterworth filter parameter / stop frequence: 30Hz / sample rate: 4K */
// const BTF_Para_TypeDef BTF_E_2O_30Hz_4K[3];
// const BTF_Para_TypeDef BTF_U_2O_30Hz_4K[2];

/* 2 order butterworth filter parameter / stop frequence: 50Hz / sample rate: 4K */
// const BTF_Para_TypeDef BTF_E_2O_50Hz_4K[3];
// const BTF_Para_TypeDef BTF_U_2O_50Hz_4K[2];

/* 3 order butterworth filter parameter / stop frequence: 30Hz / sample rate: 4K */
// const BTF_Para_TypeDef BTF_E_3O_30Hz_4K[4];
// const BTF_Para_TypeDef BTF_U_3O_30Hz_4K[3];

/* 3 order butterworth filter parameter / stop frequence: 50Hz / sample rate: 4K */
// const BTF_Para_TypeDef BTF_E_3O_50Hz_4K[4];
// const BTF_Para_TypeDef BTF_U_3O_50Hz_4K[3];

/* 4 order butterworth filter parameter / stop frequence: 30Hz / sample rate: 4K */
// const BTF_Para_TypeDef BTF_E_4O_30Hz_4K[5];
// const BTF_Para_TypeDef BTF_U_4O_30Hz_4K[4];

/* 4 order butterworth filter parameter / stop frequence: 50Hz / sample rate: 4K */
// const BTF_Para_TypeDef BTF_E_4O_50Hz_4K[5];
// const BTF_Para_TypeDef BTF_U_4O_50Hz_4K[4];

/* 5 order butterworth filter parameter / stop frequence: 30Hz / sample rate: 4K */
// const BTF_Para_TypeDef BTF_E_5O_30Hz_4K[6];
// const BTF_Para_TypeDef BTF_U_5O_30Hz_4K[5];

/* 5 order butterworth filter parameter / stop frequence: 50Hz / sample rate: 4K */
// const BTF_Para_TypeDef BTF_E_5O_50Hz_4K[6];
// const BTF_Para_TypeDef BTF_U_5O_50Hz_4K[5];
