#ifndef __SYSTEM_CFG_H
#define __SYSTEM_CFG_H

#define KERNEL_DCACHE_STATE 0
#define KERNEL_ICACHE_STATE 0

#define US_IN_1S REAL_1S
#define SCHEDULER_TIMEBASE US_IN_1S

#define EXTERNAL_RAM_MODULE 1
#define EXTERNAL_STORAGE_MODULE 1

#define KERNEL_LOWEST_INTERRUPT_PRIORITY 15
#define MAX_SYSCALL_INTERRUPT_PRIORITY 3

#define SYSCALL_INTERRUPT_PRIORITY (MAX_SYSCALL_INTERRUPT_PRIORITY << 4)

#endif
