#ifndef __SYSTEM_CFG_H
#define __SYSTEM_CFG_H

#define US_IN_1S REAL_1S
#define SCHEDULER_TIMEBASE US_IN_1S

#define EXTERNAL_INTERFACE_TYPE_SPI_FLASH (1 << 0)
#define EXTERNAL_INTERFACE_TYPE_TF_CARD (1 << 1)

#define STORAGE_MODULE EXTERNAL_INTERFACE_TYPE_TF_CARD

#define KERNEL_LOWEST_INTERRUPT_PRIORITY 15
#define MAX_SYSCALL_INTERRUPT_PRIORITY 3

#define SYSCALL_INTERRUPT_PRIORITY (MAX_SYSCALL_INTERRUPT_PRIORITY << 4)

#define TCM_ATTRIBUTE __attribute__((section(".Fast_Mem_Section")))

#define RECEIVER_PORT UART4
#define RECEIVER_CRSF_RX_DMA Bsp_DMA_None               // Bsp_DMA_1
#define RECEIVER_CRSF_RX_DMA_STREAM Bsp_DMA_Stream_None // Bsp_DMA_Stream_4
#define RECEIVER_CRSF_TX_DMA Bsp_DMA_None               // Bsp_DMA_1
#define RECEIVER_CRSF_TX_DMA_STREAM Bsp_DMA_Stream_None // Bsp_DMA_Stream_5
#define RECEIVER_SBUS_RX_DMA Bsp_DMA_1
#define RECEIVER_SBUS_RX_DMA_STREAM Bsp_DMA_Stream_4
#define RECEIVER_SBUS_TX_DMA Bsp_DMA_1
#define RECEIVER_SBUS_TX_DMA_STREAM Bsp_DMA_Stream_5

#endif
