#ifndef __SYSTEM_CFG_H
#define __SYSTEM_CFG_H

#define US_IN_1S REAL_1S
#define SCHEDULER_TIMEBASE US_IN_1S

#define EXTERNAL_INTERFACE_TYPE_SPI_FLASH (1 << 0)
#define EXTERNAL_INTERFACE_TYPE_TF_CARD (1 << 1)

#define EXTERNAL_RAM_MODULE 1
#define EXTERNAL_STORAGE_MODULE (EXTERNAL_INTERFACE_TYPE_SPI_FLASH | EXTERNAL_INTERFACE_TYPE_TF_CARD)

#define KERNEL_LOWEST_INTERRUPT_PRIORITY 15
#define MAX_SYSCALL_INTERRUPT_PRIORITY 3

#define SYSCALL_INTERRUPT_PRIORITY (MAX_SYSCALL_INTERRUPT_PRIORITY << 4)

#endif
